services:
  - type: web
    name: ai-educative-frontend
    env: static
    buildCommand: cd ai-learning-frontend && npm install && npm run build
    staticPublishPath: ai-learning-frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
